/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open an account
         * @description Resolves the registration IP to a region (ip-location-db) which becomes the account's shard key for horizontal fragmentation (v2 §7.1).
         */
        post: operations["openAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{accountId}/deposits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deposit money */
        post: operations["deposit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{accountId}/withdrawals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Withdraw money
         * @description The command is published to the account.commands topic keyed by accountId; the consumer applies it under RFairLock("account-lock:{accountId}") (v2 §5).
         */
        post: operations["withdraw"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transfer money between accounts
         * @description Orchestrated by the transfer saga (docs/SAGA_DESIGN.md).
         */
        post: operations["transfer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transfers/{transferId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get transfer saga status
         * @description Saga progress for the transfer stepper UI (docs/SAGA_DESIGN.md §1): each status maps to a saga step (INITIATED → SOURCE_DEBITED → TARGET_CREDITED → COMPLETED; FAILED/COMPENSATED on the compensation path).
         */
        get: operations["getTransferStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccountSnapshot: {
            /** Format: uuid */
            accountId?: string;
            holderName?: string;
            /**
             * @description Resolved from registrationIp; the horizontal shard key (v2 §7.1)
             * @enum {string}
             */
            region?: "APAC" | "EU" | "AMER";
            /** Format: double */
            availableBalance?: number;
            /** Format: double */
            reservedBalance?: number;
            /** Format: date-time */
            openedAt?: string;
        };
        TransferStatusView: {
            /** Format: uuid */
            transferId?: string;
            /** Format: uuid */
            fromAccountId?: string;
            /** Format: uuid */
            toAccountId?: string;
            /** Format: double */
            amount?: number;
            /**
             * @description Saga progress; FAILED/COMPENSATED mean TransferSourceReimbursed was appended
             * @enum {string}
             */
            status?: "INITIATED" | "SOURCE_DEBITED" | "TARGET_CREDITED" | "COMPLETED" | "FAILED" | "COMPENSATED";
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            failureReason?: string | null;
        };
        AmountRequest: {
            /** Format: double */
            amount: number;
        };
    };
    responses: never;
    parameters: {
        AccountId: string;
        /** @description Client-supplied idempotency key persisted in processed_requests for 24h; retries replay the original result (v2 §6). */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    openAccount: {
        parameters: {
            query?: never;
            header: {
                /** @description Client-supplied idempotency key persisted in processed_requests for 24h; retries replay the original result (v2 §6). */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    holderName: string;
                    /** Format: ipv4 */
                    registrationIp: string;
                    /** Format: double */
                    initialDeposit: number;
                };
            };
        };
        responses: {
            /** @description Account opened (AccountOpened event appended) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountSnapshot"];
                };
            };
        };
    };
    deposit: {
        parameters: {
            query?: never;
            header: {
                /** @description Client-supplied idempotency key persisted in processed_requests for 24h; retries replay the original result (v2 §6). */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                accountId: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AmountRequest"];
            };
        };
        responses: {
            /** @description MoneyDeposited event appended */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Account not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    withdraw: {
        parameters: {
            query?: never;
            header: {
                /** @description Client-supplied idempotency key persisted in processed_requests for 24h; retries replay the original result (v2 §6). */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                accountId: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AmountRequest"];
            };
        };
        responses: {
            /** @description WithdrawCommand accepted for ordered processing */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient balance (rejected at apply time) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    transfer: {
        parameters: {
            query?: never;
            header: {
                /** @description Client-supplied idempotency key persisted in processed_requests for 24h; retries replay the original result (v2 §6). */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    fromAccountId: string;
                    /** Format: uuid */
                    toAccountId: string;
                    /** Format: double */
                    amount: number;
                };
            };
        };
        responses: {
            /** @description TransferCommand accepted (saga started) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getTransferStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transferId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current saga state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransferStatusView"];
                };
            };
            /** @description Transfer not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
