/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query transaction history */
        get: operations["listTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List accounts (read model)
         * @description Read-model view of all accounts maintained from account events (v2 §2). Added for the ops/dashboard UI; balances trail the write side until the event is consumed.
         */
        get: operations["listAccounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List recent events across all aggregates
         * @description Global event feed for the dashboard live stream — polled with `since` for incremental delivery. Ordered newest-first; served from the read model.
         */
        get: operations["listRecentEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{accountId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List events for an account
         * @description Served from the region-sharded ledger_events store (v2 §7).
         */
        get: operations["listAccountEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TransactionView: {
            /** Format: uuid */
            transactionId?: string;
            /** Format: uuid */
            accountId?: string;
            /** @enum {string} */
            type?: "DEPOSIT" | "WITHDRAWAL" | "TRANSFER_IN" | "TRANSFER_OUT" | "RESERVATION" | "CAPTURE" | "RELEASE" | "LOAN_DISBURSEMENT" | "LOAN_REPAYMENT";
            /** Format: double */
            amount?: number;
            /** Format: date-time */
            occurredAt?: string;
        };
        EventView: {
            /** Format: uuid */
            eventId?: string;
            /** Format: uuid */
            aggregateId?: string;
            version?: number;
            type?: string;
            payload?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            occurredAt?: string;
            /** @enum {string} */
            region?: "APAC" | "EU" | "AMER";
        };
        AccountSummaryView: {
            /** Format: uuid */
            accountId?: string;
            holderName?: string;
            /** @enum {string} */
            region?: "APAC" | "EU" | "AMER";
            /** Format: double */
            availableBalance?: number;
            /** Format: double */
            reservedBalance?: number;
            /** Format: date-time */
            updatedAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listTransactions: {
        parameters: {
            query?: {
                accountId?: string;
                from?: string;
                to?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of transactions from the read model */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionView"][];
                };
            };
        };
    };
    listAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All known accounts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountSummaryView"][];
                };
            };
        };
    };
    listRecentEvents: {
        parameters: {
            query?: {
                /** @description Only events with occurredAt strictly after this instant. */
                since?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent events, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventView"][];
                };
            };
        };
    };
    listAccountEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ordered event list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventView"][];
                };
            };
        };
    };
}
