/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/loans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a loan
         * @description Trust tier is snapshotted from Loan Service's local read-only cache of TrustScoreChanged events (no synchronous cross-service call, v2 §3.6).
         */
        post: operations["requestLoan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/loans/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current loan priority queue
         * @description Snapshot of the Valkey `loan:queue` scored sorted set — entries in priority order (trust tier first, FCFS within tier). `position` is 1-based; the UI polls this to show the queue reordering as tier/FCFS resolve.
         */
        get: operations["getLoanQueue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/loans/pool": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin pool balance
         * @description Current `admin_pool:balance` in Valkey — the fund the Lua pop-and-debit draws from (v2 §3.4).
         */
        get: operations["getAdminPool"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/loans/{loanId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get loan status */
        get: operations["getLoan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoanRequestView: {
            /** Format: uuid */
            loanId?: string;
            /** Format: uuid */
            accountId?: string;
            /** Format: double */
            amount?: number;
            /** @description 0=Low, 1=Medium, 2=High, 3=Excellent — snapshotted at request time */
            trustTier?: number;
            /** @enum {string} */
            status?: "QUEUED" | "WAITING_FOR_FUNDS" | "APPROVED" | "DISBURSED" | "REJECTED";
            /** Format: date-time */
            requestedAt?: string;
        };
        LoanQueueView: {
            entries?: components["schemas"]["LoanQueueEntry"][];
            /** Format: date-time */
            generatedAt?: string;
        };
        LoanQueueEntry: {
            /** Format: uuid */
            loanId?: string;
            /** Format: uuid */
            accountId?: string;
            /** Format: double */
            amount?: number;
            trustTier?: number;
            /** @enum {string} */
            status?: "QUEUED" | "WAITING_FOR_FUNDS" | "APPROVED" | "DISBURSED" | "REJECTED";
            /** @description 1-based position in priority order (tier first, FCFS within tier) */
            position?: number;
            /** Format: date-time */
            requestedAt?: string;
        };
        AdminPoolView: {
            /** Format: double */
            balance?: number;
            /** @default INR */
            currency: string;
            /** Format: date-time */
            updatedAt?: string;
        };
    };
    responses: never;
    parameters: {
        /** @description Client-supplied idempotency key persisted in processed_requests for 24h (v2 §6). */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    requestLoan: {
        parameters: {
            query?: never;
            header: {
                /** @description Client-supplied idempotency key persisted in processed_requests for 24h (v2 §6). */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    accountId: string;
                    /** Format: double */
                    amount: number;
                };
            };
        };
        responses: {
            /** @description Request queued (status QUEUED) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoanRequestView"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getLoanQueue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ordered queue snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoanQueueView"];
                };
            };
        };
    };
    getAdminPool: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pool snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPoolView"];
                };
            };
        };
    };
    getLoan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                loanId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current loan state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoanRequestView"];
                };
            };
            /** @description Loan not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
