/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List sent notifications */
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        NotificationView: {
            /** Format: uuid */
            notificationId?: string;
            /** Format: uuid */
            accountId?: string;
            /** @enum {string} */
            channel?: "EMAIL";
            subject?: string;
            /** @description e.g. LoanApproved, FundsCaptured, TrustScoreChanged */
            causeEvent?: string;
            /**
             * @description SMTP delivery state; RETRYING/DEAD_LETTERED surface the DLQ state the bank log shows
             * @enum {string}
             */
            deliveryStatus?: "SENT" | "RETRYING" | "DEAD_LETTERED";
            /** Format: date-time */
            sentAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listNotifications: {
        parameters: {
            query?: {
                accountId?: string;
                /** @description Filter by originating event type, e.g. TrustScoreChanged. */
                causeEvent?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sent notifications */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationView"][];
                };
            };
        };
    };
}
