/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/reservations/{reservationId}/void": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Void a reservation (bank action)
         * @description Manually releases an active hold before TTL expiry: appends FundsReleased with reason MANUAL_VOID and returns the funds to available. 409 if the reservation is not RESERVED (already captured/expired/released).
         */
        post: operations["voidReservation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Make an online payment
         * @description Synchronous path — Account Command validates and appends MoneyWithdrawn/MoneyDeposited (v2 §4.1).
         */
        post: operations["payOnline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reservations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List reservations
         * @description All reservations newest-first. Scope with accountId (customer's own holds) or status (bank's reservations overview). Bank view includes every customer; a manually voided hold shows as RELEASED.
         */
        get: operations["listReservations"];
        put?: never;
        /**
         * Create an offline-payment reservation
         * @description Moves amount from available_balance to reserved_balance (FundsReserved event, optimistic concurrency as in v1) and mints a signed offline token containing {reservationId, accountId, amount, expiresAt} (v2 §4.2 steps 1–3).
         */
        post: operations["createReservation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reservations/{reservationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get reservation status */
        get: operations["getReservation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reservations/{reservationId}/capture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Capture a reservation (merchant redeems the offline token)
         * @description Called when the merchant device regains connectivity. First capture wins — the redeemed idempotency check keyed by reservationId rejects any replay of the same token (offline double-spend prevention, v2 §4.2 step 5). Emits FundsCaptured; the hold is converted into a real debit.
         */
        post: operations["captureReservation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ReservationView: {
            /** Format: uuid */
            reservationId?: string;
            /** Format: uuid */
            accountId?: string;
            /** Format: double */
            amount?: number;
            /** @enum {string} */
            status?: "RESERVED" | "CAPTURED" | "RELEASED" | "EXPIRED";
            /** Format: date-time */
            expiresAt?: string;
            /** Format: date-time */
            capturedAt?: string | null;
            /** @description Signed offline payment token (QR-code payload); only returned at creation time. */
            offlineToken?: string;
        };
    };
    responses: never;
    parameters: {
        ReservationId: string;
        /** @description Client-supplied idempotency key persisted in processed_requests for 24h (v2 §6). */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    voidReservation: {
        parameters: {
            query?: never;
            header: {
                /** @description Client-supplied idempotency key persisted in processed_requests for 24h (v2 §6). */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                reservationId: components["parameters"]["ReservationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Hold released */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationView"];
                };
            };
            /** @description Reservation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Reservation not active */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    payOnline: {
        parameters: {
            query?: never;
            header: {
                /** @description Client-supplied idempotency key persisted in processed_requests for 24h (v2 §6). */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    fromAccountId: string;
                    /** Format: uuid */
                    toAccountId: string;
                    /** Format: double */
                    amount: number;
                };
            };
        };
        responses: {
            /** @description Payment completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient funds or invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listReservations: {
        parameters: {
            query?: {
                accountId?: string;
                status?: components["schemas"]["ReservationView"]["status"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reservations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationView"][];
                };
            };
        };
    };
    createReservation: {
        parameters: {
            query?: never;
            header: {
                /** @description Client-supplied idempotency key persisted in processed_requests for 24h (v2 §6). */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    accountId: string;
                    /** Format: double */
                    amount: number;
                    /**
                     * @description Reservation TTL; an expiry job later publishes FundsReleased for uninvoked holds.
                     * @default 30
                     */
                    ttlMinutes?: number;
                };
            };
        };
        responses: {
            /** @description Reservation created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationView"];
                };
            };
        };
    };
    getReservation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reservationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current reservation state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationView"];
                };
            };
            /** @description Reservation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    captureReservation: {
        parameters: {
            query?: never;
            header: {
                /** @description Client-supplied idempotency key persisted in processed_requests for 24h (v2 §6). */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                reservationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Signed Nimbus JOSE+JWT token; signature and expiry verified against the reservation record. */
                    offlineToken: string;
                    /** Format: uuid */
                    merchantAccountId: string;
                };
            };
        };
        responses: {
            /** @description FundsCaptured — transfer to merchant finalized */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Reservation already captured / replayed token rejected */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Reservation expired (FundsReleased already emitted) */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
