/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/ops/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service registry snapshot */
        get: operations["listServiceInstances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/shards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Database shard status
         * @description One entry per physical Postgres shard; region mapping per v2 §7.1.
         */
        get: operations["listShards"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/kafka": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kafka topics and consumer lag */
        get: operations["listKafkaTopics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ServiceInstanceView: {
            /** @description Eureka service id, e.g. account-command-service */
            serviceId?: string;
            instanceId?: string;
            host?: string;
            port?: number;
            /** @enum {string} */
            status?: "UP" | "DOWN" | "STARTING";
            /** Format: date-time */
            registeredAt?: string;
        };
        ShardView: {
            /** @description Physical shard name, e.g. ledger_eu */
            shardId?: string;
            /** @enum {string} */
            region?: "APAC" | "EU" | "AMER";
            host?: string;
            port?: number;
            /** @enum {string} */
            status?: "UP" | "DOWN";
            /** @description Table name → row count (for example ledger_events → 1234) */
            rowCounts?: {
                [key: string]: number;
            };
        };
        KafkaTopicView: {
            /** @description e.g. account.events (partition-per-account for commands, docs/EVENT_CATALOG.md) */
            topic?: string;
            partitions?: number;
            groups?: components["schemas"]["KafkaGroupLag"][];
        };
        KafkaGroupLag: {
            groupId?: string;
            /** @description Total unconsumed messages across partitions */
            lag?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listServiceInstances: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registered instances (from Eureka) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceInstanceView"][];
                };
            };
        };
    };
    listShards: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Region shards */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShardView"][];
                };
            };
        };
    };
    listKafkaTopics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Topic lag overview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KafkaTopicView"][];
                };
            };
        };
    };
}
