/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/trust-score/{accountId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current trust score and tier for an account */
        get: operations["getTrustScore"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trust-score/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cross-customer feed of TrustScoreChanged
         * @description Audit view over the TrustScoreChanged events the service has published — why a tier moved (deposit, repayment, default). Bank-facing; newest first.
         */
        get: operations["listTrustScoreChanges"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TrustScoreView: {
            /** Format: uuid */
            accountId?: string;
            score?: number;
            /** @description 0=Low (0–40), 1=Medium (41–70), 2=High (71–90), 3=Excellent (91–100) */
            tier?: number;
            /** Format: date-time */
            lastChangedAt?: string;
        };
        TrustScoreChangeView: {
            /** Format: uuid */
            eventId?: string;
            /** Format: uuid */
            accountId?: string;
            scoreBefore?: number;
            scoreAfter?: number;
            tierBefore?: number;
            tierAfter?: number;
            /** @description e.g. DEPOSIT, LOAN_REPAYMENT, LOAN_DEFAULT, PERIODIC_REVIEW */
            reason?: string;
            /** Format: date-time */
            changedAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getTrustScore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current score and tier */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrustScoreView"];
                };
            };
            /** @description Account has no trust score yet */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listTrustScoreChanges: {
        parameters: {
            query?: {
                accountId?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Change feed, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrustScoreChangeView"][];
                };
            };
        };
    };
}
